title: Documentation
description: My Personal Blog
author: Raden Parhanudin
logo: https://codeasashu.github.io/hcz-jekyll-blog/static/img/avatar.png
github: https://github.com/radenparhanudin
about: Freelance developer

baseurl: "https://radenparhanudin.github.io/Documentation"
url: "https://codeasashu.github.io/hcz-jekyll-blog"

allowsearch: true

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
